### ISSUE TITLE
intel-ipmi-oem build fail

### ISSUE THREAD

**Issue by MattWiW** [openbmc/intel-ipmi-oem#2]
Dears,
I have a build issuse of intel-ipmi-oem after git clone the latest code and try to build the meta-intel/meta-s2600wf/.

The log indicates the following ERROR:
| /home/matt/OpenBMC/OpenBMC_Linux_Foundation/openbmc/build/tmp/work/armv6-openbmc-linux-gnueabi/intel-ipmi-oem/0.1+gitAUTOINC+b1cc61d2a0-r0/git/src/smbiosmdrv2handler.cpp:36:10: fatal error: xyz/openbmc_project/Smbios/MDR_V2/error.hpp: No such file or directory
|  #include <xyz/openbmc_project/Smbios/MDR_V2/error.hpp>
|           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This is caused by this recipe trying to go to make src/smbiosmdrv2handler.cpp.
Do you have any idea on this issue?

**Comment by vmauery** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/intel-ipmi-oem/+/22728 should address this issue.

**Comment by MattWiW** [comment]
Thanks, it's work now.
