### ISSUE TITLE
intel-ipmi-oem build fail on ast2600-default

### ISSUE THREAD

**Issue by Edward0320** [openbmc/intel-ipmi-oem#7]
Dears,
I am a new on openBMC, and I have a build issuse of intel-ipmi-oem, I try to build the ast2600-default, I add intel-ipmi-oem into my bblayers.conf.
 
The log indicates the following ERROR:

| In file included from /home/edward/OpenBmc/openbmc/build/ast2600-default/tmp/work/armv7ahf-vfpv4d16-openbmc-linux-gnueabi/intel-ipmi-oem/0.1+gitAUTOINC+6346e98cd5-r0/git/include/ipmi_to_redfish_hooks.hpp:20,
|                  from /home/edward/OpenBmc/openbmc/build/ast2600-default/tmp/work/armv7ahf-vfpv4d16-openbmc-linux-gnueabi/intel-ipmi-oem/0.1+gitAUTOINC+6346e98cd5-r0/git/src/sensorcommands.cpp:20:
| /home/edward/OpenBmc/openbmc/build/ast2600-default/tmp/work/armv7ahf-vfpv4d16-openbmc-linux-gnueabi/intel-ipmi-oem/0.1+gitAUTOINC+6346e98cd5-r0/git/include/storagecommands.hpp:18:10: fatal error: phosphor-ipmi-host/sensorhandler.hpp: No such file or directory
|    18 | #include <phosphor-ipmi-host/sensorhandler.hpp>
|       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| compilation terminated.

Do you have any idea on this issue?

**Comment by OguzhanCaglar** [comment]
Hi edward, I have the same error. How did you solve this?

**Comment by Edward0320** [comment]
Hi OguzhanCaglar,

I build the image base on ast2600-defaultl I found two way to solve the problem like this :
1. I add a phosphor-ipmi-host_%.bbappend, you can check the attach file.
2. Modify the phosphor-ipmi-host_%.bbappend in meta-intel-openbmc/meta-common/recipes-phosphor/ipmi, I remove the "intel" string.
 
I am a new one in openBMC,so I am not sure those ways correct or not, but it is the solution that I found.
I hope those can help you

![reference](https://user-images.githubusercontent.com/109523699/185739563-311ed816-1644-4fcf-8c97-982d5d26a0c9.png)

**Comment by OguzhanCaglar** [comment]
Thank you Edward, I successfully built. Do you know how to send the SMBIOS table from BIOS to BMC when BIOS is booting?
